# This is a basic workflow to help you get started with Actions

name: Pytest_conduit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9.5]

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose up -d

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
    
    - name: Test with pytest
      run: |
        pytest
